//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaDiego.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Factura
    {
        public int id_detalle { get; set; }
        public int id_factura { get; set; }
        public int id_producto { get; set; }
        public string descricion { get; set; }
        public decimal cantidad { get; set; }
        public decimal precio_unitario { get; set; }
        public Nullable<decimal> descuento_porcentaje { get; set; }
        public Nullable<decimal> descuento_valor { get; set; }
        public Nullable<decimal> iva_porcentaje { get; set; }
        public Nullable<decimal> iva_valor { get; set; }
        public decimal subtotal { get; set; }
        public decimal total { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
