//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaDiego.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.Detalle_Factura = new HashSet<Detalle_Factura>();
        }
    
        public int id_factura { get; set; }
        public string numero_fatura { get; set; }
        public int id_cliente { get; set; }
        public System.DateTime fecha_emision { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public decimal subtotal { get; set; }
        public decimal iva { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public decimal total { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Factura> Detalle_Factura { get; set; }
    }
}
